### ISSUE TITLE
Documentation mismatch: returning len from bsend/brecv

### ISSUE THREAD

**Issue by raedwulf** [sustrik/dsock#13]
The documentation states that the function return the actual number of bytes recv'd or sent in the function parameter `size_t *len`.  However, the functions only pass the parameter `len` by value.

http://libdill.org/brecv.html
http://libdill.org/bsend.html

It would be nice to have some way of returning the true length - so would the documentation be correct instead?

**Comment by sustrik** [comment]
The docs refer to the last released version (dsock-0.2-alpha).

In the github repo I have rewritten dsock heavily in the meantime. One of the changes is that these functions have become atomic. Either you get/send all bytes you asked for or none of them. Thus, there's no reason for returning the size.

**Comment by raedwulf** [comment]
Thanks! :)
