### ISSUE TITLE
Corner case/Unexpected behaviour in fdget in fd.c

### ISSUE THREAD

**Issue by raedwulf** [sustrik/dsock#15]
If `fdget` is meant to return the number of bytes read, I think you missed a corner case:
https://github.com/sustrik/dsock/blob/master/fd.c#L142

```C
static ssize_t fdget(int s, struct iovec *iov, size_t iovlen, int block,
      int64_t deadline) {
    struct msghdr hdr;
    memset(&hdr, 0, sizeof(hdr));
    size_t pos = 0;
    size_t len = iov_size(iov, iovlen);
    while(1) {
        struct iovec vec[iovlen];
        size_t veclen = iov_cut(vec, iov, iovlen, pos, len);
        hdr.msg_iov = vec;
        hdr.msg_iovlen = veclen;
        ssize_t sz = recvmsg(s, &hdr, 0);
        if(dsock_fast(sz == len)) return len;
        if(dsock_slow(sz == 0)) {errno = ECONNRESET; return -1;}
        if(dsock_slow(sz < 0 && errno != EWOULDBLOCK && errno != EAGAIN))
            return -1;
        if(dsock_fast(sz > 0)) {
            if(!block) return sz;
            pos += sz;
            len -= sz;
        }
        int rc = fdin(s, deadline);
        if(dsock_slow(rc < 0)) return -1;
    }
}
```

When `fdget` is applied as a blocking call, the `len` is decreased by `sz` per iteration of the loop.
On the second iteration,
```C
if(dsock_fast(sz == len)) return len;
```
will return the final `len` value and not the original `len` value (incidentally would be `pos`)

This does not create a bug, but it does make for unexpected behaviour if `fdget` is used for another purpose in the future.
https://github.com/sustrik/dsock/blob/master/fd.c#L179 only checks for some data read, and, 
https://github.com/sustrik/dsock/blob/master/fd.c#L177 is non-blocking so this code-path doesn't get executed.

Either extra documentation about the odd-behaviour should be given or the function should always return the total number of bytes read (for blocking calls, like it does for non-blocking calls) to make it less unexpected.

**Comment by sustrik** [comment]
Fair enough. In blocking case the function should return the original len. Feel free to send a PR.
