### ISSUE TITLE
DNS Resolver crashes after repeated name resolution

### ISSUE THREAD

**Issue by vlm** [sustrik/dsock#19]
To reproduce in the current `master`:

```
> make ./tests/dns  && ./tests/dns 
make: `tests/dns' is up to date.
Assert failed: resolver (ipaddr.c:258)
Abort trap: 6
> cat tests/dns.c 
#include <assert.h>

#include "../dsock.h"

int main() {

    /* Crash test for remote DNS resolution */
    for(int n = 0; n < 1000; n++) {
        ipaddr addr;
        (void)ipaddr_remote(&addr, "example.org", 80, IPADDR_IPV4, now() + 10);
    }

    return 0;
}
```

P.S. Mac OS X 10.12, XCode 8.0 (clang-800.0.38).

**Comment by sustrik** [comment]
Hm. It's not happening on LInux. Can you run it under debugger and check what the value of "rc" is when the assert happens?

**Comment by vlm** [comment]
Turns out, the case is easier than I thought.

```
rc = 24, errno: 24 Too many open files
```

By default, macOS's limit is 256, hence an earlier error.

However, it shouldn't crash because of that.

**Comment by sustrik** [comment]
Even so, the DNS queries are done one after another, not simultaneously. There should be one fd used. It looks like there's some kind of a leak there.

**Comment by sustrik** [comment]
This was moved to libdill in the meantime and the leak was fixed.
