### ISSUE TITLE
Intel DPDK

### ISSUE THREAD

**Issue by arafath-mk** [sustrik/dsock#27]
Hi,

Do you have plan to build dsock on top of custom TCP stack based on Intel DPDK? Please refer the `Seastar` project: https://github.com/scylladb/seastar

**Comment by sustrik** [comment]
dsock is composable. In other words, you don't have to rewrite the whole thing to use a different underlying transport protocol. Just take existing tcp transport, make a clone of it a re-write it to use DPDK. All other protocols should work on top of it without modification.

**Comment by arafath-mk** [comment]
Thanks @sustrik. Another question, if I write a web server, what about building a *net* package similar to Go's net package on top of dsock and then implementing a web server using the net package?

**Comment by sustrik** [comment]
dsock is supposed to be an equivalent of net package. what do you mean exactly?

**Comment by arafath-mk** [comment]
Hi sustrik,

I mean creating a one to one API implementation with Go's net package. In that case, people can easily port existing Go code to C for using dsock.  

I see http, websocket and TLS related files in the source code. Are those features working now? Could you please provide samples or documentation? Also, how do I use utf-8 with libdill? Do you have plan to implement the `strings` package? I think, in Go, string comparison is done using SSE..

**Comment by sustrik** [comment]
If you want Golang-style API, go on, create a wrapper library for that.

As for dsock, it's still in Alpha. TLS and http should work. There's stuff missing from websock. If you want examples, you can have a look at tests/ subdirectory.

Libdill works with binary blobs. It doesn't care whether it's ascii, utf8 or raw binary data.

**Comment by arafath-mk** [comment]
Ok @sustrik. Thanks.
