### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by systmkor** [sustrik/dsock#29]
Line `291` of the `txt` version and line `216` of the `xml` version of the RFC should be changed from `shoudl --> should`

```
shoudl be at most one connected protocol in any networking stack.
```

to
```
should be at most one connected protocol in any networking stack.
```

this didn't seem make sense to have as a fork & pull request

p.s. awesome work and really excited for a BSD Socket revamp

**Comment by sustrik** [comment]
Fixed and thanks!
