### ISSUE TITLE
Consider changing return values for all send and recv functions to ssize_t.

### ISSUE THREAD

**Issue by diffuse** [sustrik/dsock#4]
Sending buffers greater than 2^32 would be problematic.  

Also, this would align more closely to stand send and recv functions.

**Comment by sustrik** [comment]
Return value is either 0 (success) or -1 (error) at the moment. Number of bytes received is returned via 'len' argument.

**Comment by diffuse** [comment]
Clear misunderstanding on my part when reading through the API.
